  0%|          | 0/60 [00:00<?, ?it/s]/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sam3d/lib/python3.10/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sam3d/lib/python3.10/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sam3d/lib/python3.10/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sam3d/lib/python3.10/site-packages/torchio/data/image.py:248: UserWarning: Using TorchIO images without a torchio.SubjectsLoader in PyTorch >= 2.3 might have unexpected consequences, e.g., the collated batches will be instances of torchio.Subject with 5D images. Replace your PyTorch DataLoader with a torchio.SubjectsLoader so that the collated batch becomes a dictionary, as expected. See https://github.com/TorchIO-project/torchio/issues/1179 for more context about this issue.
  warnings.warn(message, stacklevel=1)
  2%|▏         | 1/60 [00:08<08:21,  8.51s/it]  3%|▎         | 2/60 [00:08<03:36,  3.73s/it]  5%|▌         | 3/60 [00:09<02:05,  2.20s/it]  7%|▋         | 4/60 [00:09<01:22,  1.48s/it]  8%|▊         | 5/60 [00:13<01:59,  2.17s/it] 10%|█         | 6/60 [00:13<01:26,  1.61s/it] 12%|█▏        | 7/60 [00:14<01:11,  1.34s/it] 13%|█▎        | 8/60 [00:14<00:53,  1.03s/it] 15%|█▌        | 9/60 [00:18<01:36,  1.89s/it] 17%|█▋        | 10/60 [00:18<01:10,  1.41s/it] 18%|█▊        | 11/60 [00:19<00:59,  1.21s/it] 20%|██        | 12/60 [00:19<00:45,  1.05it/s] 22%|██▏       | 13/60 [00:24<01:32,  1.96s/it] 23%|██▎       | 14/60 [00:24<01:07,  1.48s/it] 25%|██▌       | 15/60 [00:25<00:54,  1.21s/it] 27%|██▋       | 16/60 [00:25<00:43,  1.01it/s] 28%|██▊       | 17/60 [00:30<01:33,  2.16s/it] 30%|███       | 18/60 [00:30<01:08,  1.63s/it] 32%|███▏      | 19/60 [00:31<00:51,  1.26s/it] 33%|███▎      | 20/60 [00:31<00:39,  1.01it/s] 35%|███▌      | 21/60 [00:36<01:18,  2.01s/it] 37%|███▋      | 22/60 [00:36<00:57,  1.52s/it] 38%|███▊      | 23/60 [00:36<00:43,  1.16s/it] 40%|████      | 24/60 [00:37<00:33,  1.08it/s] 42%|████▏     | 25/60 [00:42<01:15,  2.16s/it] 43%|████▎     | 26/60 [00:42<00:55,  1.62s/it] 45%|████▌     | 27/60 [00:42<00:41,  1.25s/it] 47%|████▋     | 28/60 [00:43<00:31,  1.03it/s] 48%|████▊     | 29/60 [00:48<01:13,  2.38s/it] 50%|█████     | 30/60 [00:49<00:53,  1.78s/it] 52%|█████▏    | 31/60 [00:49<00:39,  1.35s/it] 53%|█████▎    | 32/60 [00:49<00:29,  1.05s/it] 55%|█████▌    | 33/60 [00:54<00:57,  2.12s/it] 57%|█████▋    | 34/60 [00:54<00:41,  1.59s/it] 58%|█████▊    | 35/60 [00:55<00:30,  1.23s/it] 60%|██████    | 36/60 [00:55<00:23,  1.00it/s] 62%|██████▏   | 37/60 [01:00<00:48,  2.10s/it] 63%|██████▎   | 38/60 [01:00<00:34,  1.58s/it] 65%|██████▌   | 39/60 [01:01<00:25,  1.21s/it] 67%|██████▋   | 40/60 [01:01<00:19,  1.05it/s] 68%|██████▊   | 41/60 [01:06<00:42,  2.25s/it] 70%|███████   | 42/60 [01:07<00:30,  1.68s/it] 72%|███████▏  | 43/60 [01:07<00:21,  1.29s/it] 73%|███████▎  | 44/60 [01:07<00:16,  1.03s/it] 75%|███████▌  | 45/60 [01:12<00:31,  2.09s/it] 77%|███████▋  | 46/60 [01:12<00:21,  1.57s/it] 78%|███████▊  | 47/60 [01:13<00:15,  1.21s/it] 80%|████████  | 48/60 [01:13<00:11,  1.06it/s] 82%|████████▏ | 49/60 [01:18<00:23,  2.10s/it] 83%|████████▎ | 50/60 [01:18<00:15,  1.57s/it] 85%|████████▌ | 51/60 [01:19<00:11,  1.28s/it] 87%|████████▋ | 52/60 [01:19<00:07,  1.00it/s] 88%|████████▊ | 53/60 [01:24<00:15,  2.21s/it] 90%|█████████ | 54/60 [01:25<00:09,  1.65s/it] 92%|█████████▏| 55/60 [01:25<00:06,  1.26s/it] 93%|█████████▎| 56/60 [01:25<00:04,  1.01s/it] 95%|█████████▌| 57/60 [01:30<00:06,  2.21s/it] 97%|█████████▋| 58/60 [01:31<00:03,  1.65s/it] 98%|█████████▊| 59/60 [01:31<00:01,  1.26s/it]100%|██████████| 60/60 [01:31<00:00,  1.01it/s]100%|██████████| 60/60 [01:32<00:00,  1.54s/it]
Val Inference Epoch 127:   0%|          | 0/20 [00:00<?, ?it/s]Val Inference Epoch 127:   0%|          | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 570, in <module>
    main()
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 538, in main
    trainer.train()
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 484, in train
    self.inference_on_val(epoch)
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 436, in inference_on_val
    pred_img.CopyInformation(image)
  File "/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sam3d/lib/python3.10/site-packages/SimpleITK/SimpleITK.py", line 3466, in CopyInformation
    return _SimpleITK.Image_CopyInformation(self, srcImage)
RuntimeError: Exception thrown in SimpleITK Image_CopyInformation: /tmp/SimpleITK/Code/Common/src/sitkImage.cxx:352:
sitk::ERROR: Source image size of [ 914, 464, 127 ] does not match this image's size of [ 128, 128, 128 ]!
